export const PROJECTS_REQUEST = 'PROJECTS_REQUEST';
export const PROJECTS_SUCCESS = 'PROJECTS_SUCCESS';
export const PROJECTS_ERROR = 'PROJECTS_ERROR';

export const ADD_PROJECT = 'ADD_PROJECT';
export const UPVOTE_PROJECT = 'UPVOTE_PROJECT';